/*
 * JS for firstAidOrder generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return '770347d3-7fe8-4884-9371-b993aad1f7a6';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "register",
    "location": "register.html"
}, {
    "name": "register_first_aid",
    "location": "register_first_aid.html"
}, {
    "name": "info",
    "location": "info.html"
}, {
    "name": "startScreen",
    "location": "startScreen.html"
}, {
    "name": "firstAidOrder",
    "location": "firstAidOrder.html"
}, {
    "name": "Medicine",
    "location": "Medicine.html"
}, {
    "name": "OrderStatus",
    "location": "OrderStatus.html"
}];

function firstAidOrder_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilelabel_2': 'firstAidOrder_mobilelabel_2',
        'mobileselectmenu_3': 'firstAidOrder_mobileselectmenu_3',
        'mobileselectmenu_3-0': 'firstAidOrder_mobileselectmenu_3-0'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.datasources = Apperyio.datasources || {};

    Apperyio.CurrentScreen = 'firstAidOrder';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var firstAidOrder_onLoad = function() {
            firstAidOrder_elementsExtraJS();

            firstAidOrder_deviceEvents();
            firstAidOrder_windowEvents();
            firstAidOrder_elementsEvents();
        };

    // screen window events


    function firstAidOrder_windowEvents() {

        $('#firstAidOrder').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    };

    // device events


    function firstAidOrder_deviceEvents() {
        document.addEventListener("deviceready", function() {

        });
    };

    // screen elements extra js


    function firstAidOrder_elementsExtraJS() {
        // screen (firstAidOrder) extra code

        /* mobileselectmenu_3 */

        $("#firstAidOrder_mobileselectmenu_3").parent().find("a.ui-btn").attr("tabindex", "1");

    };

    // screen elements handler


    function firstAidOrder_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

    };

    $(document).off("pagebeforeshow", "#firstAidOrder").on("pagebeforeshow", "#firstAidOrder", function(event, ui) {
        Apperyio.CurrentScreen = "firstAidOrder";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    firstAidOrder_onLoad();
};

$(document).off("pagecreate", "#firstAidOrder").on("pagecreate", "#firstAidOrder", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    firstAidOrder_js();
});