/*
 * JS for info generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return '770347d3-7fe8-4884-9371-b993aad1f7a6';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "register",
    "location": "register.html"
}, {
    "name": "register_first_aid",
    "location": "register_first_aid.html"
}, {
    "name": "info",
    "location": "info.html"
}, {
    "name": "startScreen",
    "location": "startScreen.html"
}, {
    "name": "firstAidOrder",
    "location": "firstAidOrder.html"
}, {
    "name": "Medicine",
    "location": "Medicine.html"
}, {
    "name": "OrderStatus",
    "location": "OrderStatus.html"
}];

function info_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'search': 'info_search',
        'info_grid': 'info_info_grid',
        'mobilegridcell_3': 'info_mobilegridcell_3',
        'mobilelabel_14': 'info_mobilelabel_14',
        'mobilegridcell_4': 'info_mobilegridcell_4',
        'mobilelabel_19': 'info_mobilelabel_19',
        'mobilegridcell_5': 'info_mobilegridcell_5',
        'mobilelabel_15': 'info_mobilelabel_15',
        'mobilegridcell_6': 'info_mobilegridcell_6',
        'mobilelabel_20': 'info_mobilelabel_20',
        'mobilegridcell_7': 'info_mobilegridcell_7',
        'mobilelabel_16': 'info_mobilelabel_16',
        'mobilegridcell_8': 'info_mobilegridcell_8',
        'mobilelink_26': 'info_mobilelink_26',
        'mobilegridcell_9': 'info_mobilegridcell_9',
        'mobilelabel_24': 'info_mobilelabel_24',
        'mobilegridcell_10': 'info_mobilegridcell_10',
        'mobilelabel_22': 'info_mobilelabel_22'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.datasources = Apperyio.datasources || {};

    Apperyio.CurrentScreen = 'info';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var info_onLoad = function() {
            info_elementsExtraJS();

            info_deviceEvents();
            info_windowEvents();
            info_elementsEvents();
        };

    // screen window events


    function info_windowEvents() {

        $('#info').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    };

    // device events


    function info_deviceEvents() {
        document.addEventListener("deviceready", function() {

        });
    };

    // screen elements extra js


    function info_elementsExtraJS() {
        // screen (info) extra code

    };

    // screen elements handler


    function info_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

        $(document).off("vclick", "#info_search-cover-img").on({
            vclick: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio('info_grid').show();
                }
            }
        }, "#info_search-cover-img");

    };

    $(document).off("pagebeforeshow", "#info").on("pagebeforeshow", "#info", function(event, ui) {
        Apperyio.CurrentScreen = "info";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    info_onLoad();
};

$(document).off("pagecreate", "#info").on("pagecreate", "#info", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    info_js();
});