/*
 * JS for Medicine generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return '770347d3-7fe8-4884-9371-b993aad1f7a6';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "register",
    "location": "register.html"
}, {
    "name": "register_first_aid",
    "location": "register_first_aid.html"
}, {
    "name": "info",
    "location": "info.html"
}, {
    "name": "startScreen",
    "location": "startScreen.html"
}, {
    "name": "firstAidOrder",
    "location": "firstAidOrder.html"
}, {
    "name": "Medicine",
    "location": "Medicine.html"
}, {
    "name": "OrderStatus",
    "location": "OrderStatus.html"
}];

function Medicine_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilelabel_42': 'Medicine_mobilelabel_42',
        'mobilelabel_3': 'Medicine_mobilelabel_3',
        'select_disease': 'Medicine_select_disease',
        'select_disease-0': 'Medicine_select_disease-0',
        'med_lbl': 'Medicine_med_lbl',
        'hd_select': 'Medicine_hd_select',
        'hd_select-0': 'Medicine_hd_select-0',
        'di_select': 'Medicine_di_select',
        'di_select-0': 'Medicine_di_select-0',
        'bp_select': 'Medicine_bp_select',
        'bp_select-0': 'Medicine_bp_select-0',
        'med_image': 'Medicine_med_image',
        'order': 'Medicine_order',
        'mobilegrid_34': 'Medicine_mobilegrid_34',
        'mobilegridcell_35': 'Medicine_mobilegridcell_35',
        'mobilegridcell_36': 'Medicine_mobilegridcell_36',
        'mobilegridcell_37': 'Medicine_mobilegridcell_37',
        'mobilegridcell_38': 'Medicine_mobilegridcell_38',
        'mobilegrid_52': 'Medicine_mobilegrid_52',
        'mobilegridcell_53': 'Medicine_mobilegridcell_53',
        'mobilelabel_57': 'Medicine_mobilelabel_57',
        'mobilegroupedbuttons_59': 'Medicine_mobilegroupedbuttons_59',
        'mobilebutton_60': 'Medicine_mobilebutton_60',
        'mobilebutton_61': 'Medicine_mobilebutton_61'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.datasources = Apperyio.datasources || {};

    Apperyio.CurrentScreen = 'Medicine';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var Medicine_onLoad = function() {
            Medicine_elementsExtraJS();

            Medicine_deviceEvents();
            Medicine_windowEvents();
            Medicine_elementsEvents();
        };

    // screen window events


    function Medicine_windowEvents() {

        $('#Medicine').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    };

    // device events


    function Medicine_deviceEvents() {
        document.addEventListener("deviceready", function() {

        });
    };

    // screen elements extra js


    function Medicine_elementsExtraJS() {
        // screen (Medicine) extra code

        /* select_disease */

        $("#Medicine_select_disease").parent().find("a.ui-btn").attr("tabindex", "5");

        /* hd_select */

        $("#Medicine_hd_select").parent().find("a.ui-btn").attr("tabindex", "6");

        /* di_select */

        $("#Medicine_di_select").parent().find("a.ui-btn").attr("tabindex", "7");

        /* bp_select */

        $("#Medicine_bp_select").parent().find("a.ui-btn").attr("tabindex", "10");

        /* popup */
        $("#Medicine_popup").popup("option", "positionTo", "window");

    };

    // screen elements handler


    function Medicine_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

        $(document).off("change", '#Medicine_mobilecontainer [name="select_disease"]').on({
            change: function(event) {
                var disease = Apperyio('select_disease').val();
                //alert(disease);
                alert((disease !== ''));
                alert(disease);

                if (disease !== '') {
                    if (disease === 'hd') {
                        Apperyio('hd_select').attr('visible', true);
                        Appery('hd_select').show();
                        Apperyio('di_select').attr('visible', false);
                        Appery('di_select').parents('[data-role="fieldcontain"]').hide();
                        Apperyio('bp_select').attr('visible', false);
                        Appery('bp_select').parents('[data-role="fieldcontain"]').hide();
                        Apperyio('med_lbl').attr('visible', true);
                        Appery('med_lbl').parents('[data-role="fieldcontain"]').show();

                    } else if (disease === 'di') {
                        alert('in Di');
                        Apperyio('hd_select').attr('visible', true);
                        Appery('hd_select').hide();
                        Apperyio('di_select').attr('visible', false);
                        Appery('di_select').parents('[data-role="fieldcontain"]').show();
                        Apperyio('bp_select').attr('visible', false);
                        Appery('bp_select').hide();
                        Apperyio('med_lbl').attr('visible', true);
                        Appery('med_lbl').show();
                    }

                };
            },
        }, '#Medicine_mobilecontainer [name="select_disease"]');

        $(document).off("change", '#Medicine_mobilecontainer [name="di_select"]').on({
            change: function(event) {
                var med_name = Apperyio('di_select').val();

                if (med_name === '') {
                    Apperyio('med_image').attr('src', '')
                }
                if (med_name === 'Insulin') {
                    Apperyio('med_image').attr('src', 'http://babalshefa.com/Media/Images/2494-2.jpg')
                }
                if (med_name === 'daonil') {
                    Apperyio('med_image').attr('src', 'https://www.dowa.co/content/images/thumbs/0002136_daonil-5mg-100tabs_600.jpeg')

                }

                if (med_name === 'glu') {
                    Apperyio('med_image').attr('src', 'http://xsteroids.com/image/cache/products%20Pix%20/Glucophage%20(Metformi)%205-500x500.jpg');

                };
            },
        }, '#Medicine_mobilecontainer [name="di_select"]');

        $(document).off("click", '#Medicine_mobilecontainer [name="order"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    var popupElement = Apperyio("popup");
                    if (popupElement.popup("option", "positionTo") === "origin") {
                        popupElement.popup("open", {
                            transition: "fade",
                            positionTo: "#" + $(this).attr("id")
                        });
                    } else {
                        popupElement.popup("open", {
                            transition: "fade"
                        });
                    };

                }
            },
        }, '#Medicine_mobilecontainer [name="order"]');

        $(document).off("click", '#Medicine_popup [name="mobilebutton_60"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    setTimeout(function() {
                        window.location = 'OrderStatus.html';
                    }, 0);

                }
            },
        }, '#Medicine_popup [name="mobilebutton_60"]');

    };

    $(document).off("pagebeforeshow", "#Medicine").on("pagebeforeshow", "#Medicine", function(event, ui) {
        Apperyio.CurrentScreen = "Medicine";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    Medicine_onLoad();
};

$(document).off("pagecreate", "#Medicine").on("pagecreate", "#Medicine", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    Medicine_js();
});