/*
 * JS for register_first_aid generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return '770347d3-7fe8-4884-9371-b993aad1f7a6';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "register",
    "location": "register.html"
}, {
    "name": "register_first_aid",
    "location": "register_first_aid.html"
}, {
    "name": "info",
    "location": "info.html"
}, {
    "name": "startScreen",
    "location": "startScreen.html"
}, {
    "name": "firstAidOrder",
    "location": "firstAidOrder.html"
}, {
    "name": "Medicine",
    "location": "Medicine.html"
}, {
    "name": "OrderStatus",
    "location": "OrderStatus.html"
}];

function register_first_aid_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilegrid_2': 'register_first_aid_mobilegrid_2',
        'mobilegridcell_3': 'register_first_aid_mobilegridcell_3',
        'mobilelabel_7': 'register_first_aid_mobilelabel_7',
        'mobilegridcell_4': 'register_first_aid_mobilegridcell_4',
        'reg_name': 'register_first_aid_reg_name',
        'mobilegridcell_5': 'register_first_aid_mobilegridcell_5',
        'mobilelabel_8': 'register_first_aid_mobilelabel_8',
        'mobilegridcell_6': 'register_first_aid_mobilegridcell_6',
        'reg_age': 'register_first_aid_reg_age',
        'mobilegridcell_9': 'register_first_aid_mobilegridcell_9',
        'mobilelabel_15': 'register_first_aid_mobilelabel_15',
        'mobilegridcell_10': 'register_first_aid_mobilegridcell_10',
        'reg_disease_date': 'register_first_aid_reg_disease_date',
        'mobilegridcell_11': 'register_first_aid_mobilegridcell_11',
        'mobilelabel_16': 'register_first_aid_mobilelabel_16',
        'mobilegridcell_12': 'register_first_aid_mobilegridcell_12',
        'reg_id': 'register_first_aid_reg_id',
        'mobilegridcell_13': 'register_first_aid_mobilegridcell_13',
        'mobilelabel_17': 'register_first_aid_mobilelabel_17',
        'mobilegridcell_14': 'register_first_aid_mobilegridcell_14',
        'reg_nat': 'register_first_aid_reg_nat',
        'reg_nat-0': 'register_first_aid_reg_nat-0',
        'order_fa': 'register_first_aid_order_fa'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.datasources = Apperyio.datasources || {};

    Apperyio.CurrentScreen = 'register_first_aid';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var register_first_aid_onLoad = function() {
            register_first_aid_elementsExtraJS();

            register_first_aid_deviceEvents();
            register_first_aid_windowEvents();
            register_first_aid_elementsEvents();
        };

    // screen window events


    function register_first_aid_windowEvents() {

        $('#register_first_aid').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    };

    // device events


    function register_first_aid_deviceEvents() {
        document.addEventListener("deviceready", function() {

        });
    };

    // screen elements extra js


    function register_first_aid_elementsExtraJS() {
        // screen (register_first_aid) extra code

        /* reg_disease_date */

        register_first_aid_reg_disease_date_selector = "#register_first_aid_reg_disease_date";
        register_first_aid_reg_disease_date_dataPickerOptions = {
            dateFormat: "mm/dd/yy",
            firstDay: 0,

            maxDate: new Date(""),

            minDate: new Date(""),

            dayNamesMin: ['Su', 'Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa'],
            monthNames: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
            showOtherMonths: true
        };

        register_first_aid_reg_disease_date_dataPickerOptions.defaultDate = new Date("08/03/2018");

        Apperyio.__registerComponent('reg_disease_date', new Apperyio.ApperyMobileDatePickerComponent("register_first_aid_reg_disease_date", register_first_aid_reg_disease_date_dataPickerOptions));

        /* reg_nat */

        $("#register_first_aid_reg_nat").parent().find("a.ui-btn").attr("tabindex", "7");

    };

    // screen elements handler


    function register_first_aid_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

        $(document).off("click", '#register_first_aid_mobilecontainer [name="order_fa"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('Medicine', {
                        reverse: false
                    });

                }
            },
        }, '#register_first_aid_mobilecontainer [name="order_fa"]');

    };

    $(document).off("pagebeforeshow", "#register_first_aid").on("pagebeforeshow", "#register_first_aid", function(event, ui) {
        Apperyio.CurrentScreen = "register_first_aid";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    register_first_aid_onLoad();
};

$(document).off("pagecreate", "#register_first_aid").on("pagecreate", "#register_first_aid", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    register_first_aid_js();
});