/*
 * JS for register generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return '770347d3-7fe8-4884-9371-b993aad1f7a6';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "register",
    "location": "register.html"
}, {
    "name": "register_first_aid",
    "location": "register_first_aid.html"
}, {
    "name": "info",
    "location": "info.html"
}, {
    "name": "startScreen",
    "location": "startScreen.html"
}, {
    "name": "firstAidOrder",
    "location": "firstAidOrder.html"
}, {
    "name": "Medicine",
    "location": "Medicine.html"
}, {
    "name": "OrderStatus",
    "location": "OrderStatus.html"
}];

function register_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilegrid_2': 'register_mobilegrid_2',
        'mobilegridcell_3': 'register_mobilegridcell_3',
        'mobilelabel_7': 'register_mobilelabel_7',
        'mobilegridcell_4': 'register_mobilegridcell_4',
        'reg_name': 'register_reg_name',
        'mobilegridcell_5': 'register_mobilegridcell_5',
        'mobilelabel_8': 'register_mobilelabel_8',
        'mobilegridcell_6': 'register_mobilegridcell_6',
        'reg_age': 'register_reg_age',
        'mobilegridcell_9': 'register_mobilegridcell_9',
        'mobilelabel_15': 'register_mobilelabel_15',
        'mobilegridcell_10': 'register_mobilegridcell_10',
        'reg_disease': 'register_reg_disease',
        'mobilegridcell_11': 'register_mobilegridcell_11',
        'mobilelabel_16': 'register_mobilelabel_16',
        'mobilegridcell_12': 'register_mobilegridcell_12',
        'reg_id': 'register_reg_id',
        'mobilegridcell_13': 'register_mobilegridcell_13',
        'mobilelabel_17': 'register_mobilelabel_17',
        'mobilegridcell_14': 'register_mobilegridcell_14',
        'reg_nat': 'register_reg_nat',
        'reg_nat-0': 'register_reg_nat-0',
        'mobilebutton_23': 'register_mobilebutton_23'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.datasources = Apperyio.datasources || {};

    Apperyio.CurrentScreen = 'register';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var register_onLoad = function() {
            register_elementsExtraJS();

            register_deviceEvents();
            register_windowEvents();
            register_elementsEvents();
        };

    // screen window events


    function register_windowEvents() {

        $('#register').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    };

    // device events


    function register_deviceEvents() {
        document.addEventListener("deviceready", function() {

        });
    };

    // screen elements extra js


    function register_elementsExtraJS() {
        // screen (register) extra code

        /* reg_nat */

        $("#register_reg_nat").parent().find("a.ui-btn").attr("tabindex", "7");

    };

    // screen elements handler


    function register_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

        $(document).off("click", '#register_mobilecontainer [name="mobilebutton_23"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('Medicine', {
                        reverse: false
                    });

                }
            },
        }, '#register_mobilecontainer [name="mobilebutton_23"]');

    };

    $(document).off("pagebeforeshow", "#register").on("pagebeforeshow", "#register", function(event, ui) {
        Apperyio.CurrentScreen = "register";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    register_onLoad();
};

$(document).off("pagecreate", "#register").on("pagecreate", "#register", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    register_js();
});