/*
 * JS for startScreen generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return '770347d3-7fe8-4884-9371-b993aad1f7a6';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "register",
    "location": "register.html"
}, {
    "name": "register_first_aid",
    "location": "register_first_aid.html"
}, {
    "name": "info",
    "location": "info.html"
}, {
    "name": "startScreen",
    "location": "startScreen.html"
}, {
    "name": "firstAidOrder",
    "location": "firstAidOrder.html"
}, {
    "name": "Medicine",
    "location": "Medicine.html"
}, {
    "name": "OrderStatus",
    "location": "OrderStatus.html"
}];

function startScreen_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilecarousel_5': 'startScreen_mobilecarousel_5',
        'mobilecarouselitem_6': 'startScreen_mobilecarouselitem_6',
        'mobileimage_10': 'startScreen_mobileimage_10',
        'mobilecarouselitem_7': 'startScreen_mobilecarouselitem_7',
        'mobileimage_11': 'startScreen_mobileimage_11',
        'mobilebutton_3': 'startScreen_mobilebutton_3',
        'mobilebutton_21': 'startScreen_mobilebutton_21',
        'mobilebutton_4': 'startScreen_mobilebutton_4'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.datasources = Apperyio.datasources || {};

    Apperyio.CurrentScreen = 'startScreen';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var startScreen_onLoad = function() {
            startScreen_elementsExtraJS();

            startScreen_deviceEvents();
            startScreen_windowEvents();
            startScreen_elementsEvents();
        };

    // screen window events


    function startScreen_windowEvents() {

        $('#startScreen').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    };

    // device events


    function startScreen_deviceEvents() {
        document.addEventListener("deviceready", function() {

        });
    };

    // screen elements extra js


    function startScreen_elementsExtraJS() {
        // screen (startScreen) extra code

        /* mobilecarousel_5*/
        var mobilecarousel_5_options = {
            indicatorsListClass: "ui-carousel-indicators",
            showIndicator: false,
            showTitle: true,
            titleBuildIn: false,
            titleIsText: true,
            animationDuration: 250,
            useLegacyAnimation: false,
            enabled: true,
        }
        Apperyio.__registerComponent('mobilecarousel_5', new Apperyio.ApperyMobileCarouselComponent("startScreen_mobilecarousel_5", mobilecarousel_5_options));

        $("#startScreen_mobilecarouselitem_6").attr("reRender", "mobilecarousel_5");

        $("#startScreen_mobilecarouselitem_7").attr("reRender", "mobilecarousel_5");

    };

    // screen elements handler


    function startScreen_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

        $(document).off("click", '#startScreen_mobilecontainer [name="mobilebutton_3"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('register', {
                        transition: 'fade',
                        reverse: false
                    });

                }
            },
        }, '#startScreen_mobilecontainer [name="mobilebutton_3"]');

        $(document).off("click", '#startScreen_mobilecontainer [name="mobilebutton_4"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('info', {
                        reverse: false
                    });

                }
            },
        }, '#startScreen_mobilecontainer [name="mobilebutton_4"]');

    };

    $(document).off("pagebeforeshow", "#startScreen").on("pagebeforeshow", "#startScreen", function(event, ui) {
        Apperyio.CurrentScreen = "startScreen";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    startScreen_onLoad();
};

$(document).off("pagecreate", "#startScreen").on("pagecreate", "#startScreen", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    startScreen_js();
});